/**
 * Generates Prisma seed files with embedded geographic data.
 */

interface CountrySeedData {
  name: string;
  iso2: string;
  iso3: string;
  phonecode: string;
  capital: string;
  currency: string;
}

interface StateSeedData {
  name: string;
  iso2: string;
  country_code: string;
}

interface CitySeedData {
  name: string;
}

/**
 * Generates a Prisma seed file for countries.
 */
export function generateCountrySeed(countries: CountrySeedData[]): string {
  const dataJson = countries
    .map(
      (c) =>
        `  { name: ${JSON.stringify(c.name)}, iso2: ${JSON.stringify(c.iso2)}, iso3: ${JSON.stringify(c.iso3)}, phonecode: ${JSON.stringify(c.phonecode)}, capital: ${JSON.stringify(c.capital || '')}, currency: ${JSON.stringify(c.currency)} }`
    )
    .join(',\n');

  return `// seed-countries.ts
// Generated by @countrystatecity/cli
// Data: ${countries.length} countries from countrystatecity.in

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
${dataJson}
];

async function main() {
  console.log(\`Seeding \${countries.length} countries...\`);
  await prisma.country.createMany({
    data: countries,
    skipDuplicates: true,
  });
  console.log('Done.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;
}

/**
 * Generates a Prisma seed file for states.
 */
export function generateStateSeed(states: StateSeedData[], countryCode: string): string {
  const dataJson = states
    .map(
      (s) =>
        `  { name: ${JSON.stringify(s.name)}, iso2: ${JSON.stringify(s.iso2)}, countryCode: ${JSON.stringify(s.country_code)} }`
    )
    .join(',\n');

  return `// seed-states.ts
// Generated by @countrystatecity/cli
// Data: ${states.length} states for ${countryCode} from countrystatecity.in

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const states = [
${dataJson}
];

async function main() {
  console.log(\`Seeding \${states.length} states...\`);
  await prisma.state.createMany({
    data: states,
    skipDuplicates: true,
  });
  console.log('Done.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;
}

/**
 * Generates a Prisma seed file for cities.
 */
export function generateCitySeed(cities: CitySeedData[], countryCode: string, stateCode: string): string {
  const dataJson = cities
    .map((c) => `  { name: ${JSON.stringify(c.name)} }`)
    .join(',\n');

  return `// seed-cities.ts
// Generated by @countrystatecity/cli
// Data: ${cities.length} cities for ${countryCode}/${stateCode} from countrystatecity.in

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cities = [
${dataJson}
];

async function main() {
  console.log(\`Seeding \${cities.length} cities...\`);
  await prisma.city.createMany({
    data: cities,
    skipDuplicates: true,
  });
  console.log('Done.');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
`;
}
