/**
 * Generates a self-contained React dropdown component with embedded data.
 */

interface CountryData {
  id: number;
  name: string;
  iso2: string;
  phonecode: string;
  emoji: string;
}

interface StateData {
  id: number;
  name: string;
  iso2: string;
  country_code: string;
}

interface CityData {
  id: number;
  name: string;
}

/**
 * Generates a React <select> component for countries.
 */
export function generateCountryDropdown(countries: CountryData[], tsx: boolean): string {
  const ext = tsx ? 'tsx' : 'jsx';
  const dataJson = countries
    .map(
      (c) =>
        `  { id: ${c.id}, name: ${JSON.stringify(c.name)}, iso2: ${JSON.stringify(c.iso2)}, phonecode: ${JSON.stringify(c.phonecode)}, emoji: ${JSON.stringify(c.emoji)} }`
    )
    .join(',\n');

  return `// CountrySelect.${ext}
// Generated by @countrystatecity/cli
// Data: ${countries.length} countries from countrystatecity.in

import { useState } from 'react';
${tsx ? `
interface Country {
  id: number;
  name: string;
  iso2: string;
  phonecode: string;
  emoji: string;
}

interface CountrySelectProps {
  value?: string;
  onChange?: (iso2: string, country: Country) => void;
  placeholder?: string;
  className?: string;
  disabled?: boolean;
}
` : ''}
const countries${tsx ? ': Country[]' : ''} = [
${dataJson}
];

export default function CountrySelect(${tsx ? `{
  value,
  onChange,
  placeholder = "Select a country",
  className = "",
  disabled = false,
}: CountrySelectProps` : `{
  value,
  onChange,
  placeholder = "Select a country",
  className = "",
  disabled = false,
}`}) {
  const [internalSelected, setInternalSelected] = useState(value ?? "");
  const selected = value ?? internalSelected;

  const handleChange = (e${tsx ? ': React.ChangeEvent<HTMLSelectElement>' : ''}) => {
    const iso2 = e.target.value;
    setInternalSelected(iso2);
    const country = countries.find(c => c.iso2 === iso2);
    if (onChange && country) onChange(iso2, country);
  };

  return (
    <select
      value={selected}
      onChange={handleChange}
      className={className}
      disabled={disabled}
    >
      <option value="">{placeholder}</option>
      {countries.map((c) => (
        <option key={c.iso2} value={c.iso2}>
          {c.emoji} {c.name}
        </option>
      ))}
    </select>
  );
}
`;
}

/**
 * Generates a React <select> component for states with country filtering.
 */
export function generateStateDropdown(states: StateData[], countryCode: string, tsx: boolean): string {
  const ext = tsx ? 'tsx' : 'jsx';
  const dataJson = states
    .map(
      (s) =>
        `  { id: ${s.id}, name: ${JSON.stringify(s.name)}, iso2: ${JSON.stringify(s.iso2)} }`
    )
    .join(',\n');

  return `// StateSelect.${ext}
// Generated by @countrystatecity/cli
// Data: ${states.length} states for ${countryCode} from countrystatecity.in

import { useState } from 'react';
${tsx ? `
interface State {
  id: number;
  name: string;
  iso2: string;
}

interface StateSelectProps {
  countryCode?: string;
  value?: string;
  onChange?: (iso2: string, state: State) => void;
  placeholder?: string;
  className?: string;
  disabled?: boolean;
}
` : ''}
const states${tsx ? ': State[]' : ''} = [
${dataJson}
];

export default function StateSelect(${tsx ? `{
  countryCode = "${countryCode}",
  value,
  onChange,
  placeholder = "Select a state",
  className = "",
  disabled = false,
}: StateSelectProps` : `{
  countryCode = "${countryCode}",
  value,
  onChange,
  placeholder = "Select a state",
  className = "",
  disabled = false,
}`}) {
  const [internalSelected, setInternalSelected] = useState(value ?? "");
  const selected = value ?? internalSelected;

  const handleChange = (e${tsx ? ': React.ChangeEvent<HTMLSelectElement>' : ''}) => {
    const iso2 = e.target.value;
    setInternalSelected(iso2);
    const state = states.find(s => s.iso2 === iso2);
    if (onChange && state) onChange(iso2, state);
  };

  return (
    <select
      value={selected}
      onChange={handleChange}
      className={className}
      disabled={disabled}
      data-country={countryCode}
    >
      <option value="">{placeholder}</option>
      {states.map((s) => (
        <option key={s.iso2} value={s.iso2}>
          {s.name}
        </option>
      ))}
    </select>
  );
}
`;
}

/**
 * Generates a React <select> component for cities with country+state filtering.
 */
export function generateCityDropdown(cities: CityData[], countryCode: string, stateCode: string, tsx: boolean): string {
  const ext = tsx ? 'tsx' : 'jsx';
  const dataJson = cities
    .map((c) => `  { id: ${c.id}, name: ${JSON.stringify(c.name)} }`)
    .join(',\n');

  return `// CitySelect.${ext}
// Generated by @countrystatecity/cli
// Data: ${cities.length} cities for ${countryCode}/${stateCode} from countrystatecity.in

import { useState } from 'react';
${tsx ? `
interface City {
  id: number;
  name: string;
}

interface CitySelectProps {
  countryCode?: string;
  stateCode?: string;
  value?: string;
  onChange?: (name: string, city: City) => void;
  placeholder?: string;
  className?: string;
  disabled?: boolean;
}
` : ''}
const cities${tsx ? ': City[]' : ''} = [
${dataJson}
];

export default function CitySelect(${tsx ? `{
  countryCode = "${countryCode}",
  stateCode = "${stateCode}",
  value,
  onChange,
  placeholder = "Select a city",
  className = "",
  disabled = false,
}: CitySelectProps` : `{
  countryCode = "${countryCode}",
  stateCode = "${stateCode}",
  value,
  onChange,
  placeholder = "Select a city",
  className = "",
  disabled = false,
}`}) {
  const [internalSelected, setInternalSelected] = useState(value ?? "");
  const selected = value ?? internalSelected;

  const handleChange = (e${tsx ? ': React.ChangeEvent<HTMLSelectElement>' : ''}) => {
    const name = e.target.value;
    setInternalSelected(name);
    const city = cities.find(c => c.name === name);
    if (onChange && city) onChange(name, city);
  };

  return (
    <select
      value={selected}
      onChange={handleChange}
      className={className}
      disabled={disabled}
      data-country={countryCode}
      data-state={stateCode}
    >
      <option value="">{placeholder}</option>
      {cities.map((c) => (
        <option key={c.id} value={c.name}>
          {c.name}
        </option>
      ))}
    </select>
  );
}
`;
}
